### ISSUE TITLE
What will be the backend ?

### ISSUE THREAD

**Issue by Nikhil-z** [qiscus/qiscus-sdk-android#1]
Hi , Its an interesting lib , Thanks . But i have a doubt , Where will be the chat data are stored . Can i use my own server as back-end ? . Hope to hear from you soon

**Comment by evnpr** [comment]
Hi, no you cant (at least for now).. You have to use Qiscus http://sdk.qiscus.com as your backend. BTW, What kind of app you want to build?

**Comment by Nikhil-z** [comment]
Thanks . BTW i just wanted to know thats it  :)
