### ISSUE TITLE
Could not find com.schinizer:rxunfurl:0.2.0

### ISSUE THREAD

**Issue by iffanmajid** [qiscus/qiscus-sdk-android#100]
Hello everyone, 

When I remove jCenter from my project, the dependencies could not found for following library:
 ```
> Could not find com.schinizer:rxunfurl:0.2.0.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/schinizer/rxunfurl/0.2.0/rxunfurl-0.2.0.pom
       - https://repo.maven.apache.org/maven2/com/schinizer/rxunfurl/0.2.0/rxunfurl-0.2.0.pom
       - https://jitpack.io/com/schinizer/rxunfurl/0.2.0/rxunfurl-0.2.0.pom
       - https://artifactory.qiscus.com/artifactory/qiscus-library-open-source/com/schinizer/rxunfurl/0.2.0/rxunfurl-0.2.0.pom
       - https://cardinalcommerceprod.jfrog.io/artifactory/android/com/schinizer/rxunfurl/0.2.0/rxunfurl-0.2.0.pom
     Required by:
         project :app > com.qiscus.sdk:chat-core:1.6.0
```

**Comment by ariefnurputranto** [comment]
Thanks for your report sir @iffanmajid 

you can add this code to fix this.

```
repositories {
        google()
        mavenCentral()
        maven {
            url "https://plugins.gradle.org/m2/"
        }
    }
    
    
allprojects {
    repositories {
        google()
        maven { url "https://artifactory.qiscus.com/artifactory/qiscus-library-open-source" }
        maven { url 'https://jitpack.io' }
        maven {
            url "https://plugins.gradle.org/m2/"
        }
    }
}
```

Regards

**Comment by iffanmajid** [comment]
thanks for the response. I think it works now.

**Comment by Feny-rs** [comment]
Hello everyone, I got same error too 
` Failed to transform rxunfurl-0.2.0.jar (com.schinizer:rxunfurl:0.2.0) to match attributes {artifactType=enumerated-runtime-classes, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Could not find rxunfurl-0.2.0.jar (com.schinizer:rxunfurl:0.2.0).
        Searched in the following locations:
            https://plugins.gradle.org/m2/com/schinizer/rxunfurl/0.2.0/rxunfurl-0.2.0.jar
` 
and I have added the code as suggested by @ariefnurputranto but it still can't solve. What should I do then?
