### ISSUE TITLE
Can't resolve Firebase 11.0.2 Dependencies

### ISSUE THREAD

**Issue by EdwardQuixote** [qiscus/qiscus-sdk-android#13]
With release `2.7.2` and `2.8.0` (What I've used), on Gradle Build, the gradle errors:
```
Failed to resolve: com.google.firebase:firebase-core:11.0.2
Failed to resolve: com.google.firebase:firebase-messaging:11.0.2
```

See attached file - Text file representation of my application's (Qiscus Sample App) build.gradle file.

[build_gradle.txt](https://github.com/qiscus/qiscus-sdk-android/files/1221831/build_gradle.txt)

I've also used release `1.19.0` and didn't encounter this issue.

**Comment by zetbaitsu** [comment]
Your Google Repository is obsolete.
Go to Android SDK Manager and install the latest version of below two libraries

Google Play Services
Google Repository

https://stackoverflow.com/questions/37310188/failed-to-resolve-com-google-firebasefirebase-core9-0-0
