### ISSUE TITLE
Database

### ISSUE THREAD

**Issue by pramod-khalkar** [qiscus/qiscus-sdk-android#2]
It would have been best if you could provide option for own database instead of yours

**Comment by zetbaitsu** [comment]
If you mean is local database, its can. You can implements QiscusDataStore interface to your DatabaseHelper and then set Qiscus to use your own QiscusDataStore. e.g:

``` java
public class MyDataBase implements QiscusDataStore {
        ... // Your implementation
}

Qiscus.setDataStore(new MyDataBase()); //Set Qiscus to use your DataBase
```
