### ISSUE TITLE
Send Video

### ISSUE THREAD

**Issue by ahmetoguzer** [qiscus/qiscus-sdk-android#4]
Hi, I'm using your chat application  but I don't sent video in chat.
I am trying to send video it as a file and I get  error from it.

**Comment by deltapurna** [comment]
Hi @ahmetoguzer ,

Thanks a lot for the feedback. There was some issues in our architecture previously that causing you not able to upload a video. It has been fixed now please try again.

We are sorry for the inconvenience, let us know if you still facing any problem
