### ISSUE TITLE
Back button on chat view

### ISSUE THREAD

**Issue by spidfire** [qiscus/qiscus-sdk-android#55]
![untitled](https://user-images.githubusercontent.com/156694/39989452-3f5e8928-576a-11e8-93a1-c0a5a2897171.png)

I wonder if i'm the only one but I seem to click everytime next to the back button, giving me the feel like the app is not responsive.

**Comment by andhikayuana** [comment]
thanks @spidfire, [it](https://github.com/qiscus/qiscus-sdk-android/pull/61) will be fixed in next release.
