### ISSUE TITLE
New logo

### ISSUE THREAD

**Issue by mansya** [qiscus/qiscus-sdk-android#58]
Hi, I am a graphic designer, I want to help others in graphic design.

After I reviewed your project, you have no logo on this project. Therefore I want to contribute to this project by creating a new logo / icon. what do you think?

**Comment by adicatur** [comment]
Hi there, thanks for taking the initiative, unfortunately we already have the logo qiscus.com perhaps you may give us feedback for our landing pages, thanks :)
