### ISSUE TITLE
Crash Possibility : java.lang.IllegalStateException: Apps may not schedule more than 100 distinct jobs

### ISSUE THREAD

**Issue by Krishan14sharma** [qiscus/qiscus-sdk-android#60]
https://github.com/qiscus/qiscus-sdk-android/blob/0721906847b4c422be2095763597245edac452e9/chat/src/main/java/com/qiscus/sdk/service/QiscusSyncJobService.java#L171

Qiscus SDK is creating new job ids whenever this service is called this will add new jobs every time in the job queue which will lead to this possible crash.

https://samebug.io/exceptions/2449713/java.lang.IllegalStateException/apps-may-not-schedule-more-than-100

**Comment by andhikayuana** [comment]
thanks, please see 2.26.2 version.

https://github.com/qiscus/qiscus-sdk-android/blob/cb6ab2d5d9d47a837d10b0240109571e2b678fa4/chat/src/main/java/com/qiscus/sdk/service/QiscusSyncJobService.java#L45
