### ISSUE TITLE
Glide 4 Conflict

### ISSUE THREAD

**Issue by fadhilnurmahardi** [qiscus/qiscus-sdk-android#66]
Hi qiscus!

i have issue about glide library.. my app is crashes when load image from qiscus.. is there any solution from that issue ?? i used glide 4.

Thank You!

**Comment by fadhilnurmahardi** [comment]
i'm sorry it's duplicate issue

**Comment by fadhilnurmahardi** [comment]
it is official release ?

**Comment by andhikayuana** [comment]
Not yet mas, because some method not support in glide v4, sorry about information.

You can see in glide v4  about considering old version

**Comment by andhikayuana** [comment]
<img width="781" alt="screen shot 2018-07-24 at 16 04 11" src="https://user-images.githubusercontent.com/10376354/43128280-c0e39fdc-8f5b-11e8-8152-d6e6f201921a.png">

hello mas @fadhilnurmahardi , we already update glide library to [glide v4.7.1](https://github.com/bumptech/glide/releases/tag/v4.7.1)

thanks
