### ISSUE TITLE
Upgrade to RxJava 2.0

### ISSUE THREAD

**Issue by adisiji** [qiscus/qiscus-sdk-android#71]
Please upgrade your RxJava version. Because it's too obsolete to use RxJava 1 today. 
Thank you!

**Comment by andhikayuana** [comment]
We are sorry for compatibility issues with your app, we are decide still to using RxJava 1 in this version.

We will support RxJava2 at [Qiscus SDK 3.0.0](https://github.com/qiscus/qiscus-sdk-android/tree/v3).. thanks for the feedback.
