### ISSUE TITLE
QiscusApi.getInstance().getChatRoom(roomId) returns nothing

### ISSUE THREAD

**Issue by anuress** [qiscus/qiscus-sdk-android#77]
I got no return value from running QiscusApi.getInstance().getChatRoom(roomId). Below is the code that I used.
```
QiscusApi.getInstance()
                .getChatRoom(id)
                .subscribeOn(Schedulers.io())
                .doOnNext(chatRoom -> QiscusCore.getDataStore().addOrUpdate(chatRoom))
                .observeOn(AndroidSchedulers.mainThread())
                .subscribe(onSuccess::call, onError::call);
```

**Comment by adicatur** [comment]
Hi @anuress thanks for the report, can you try again?

**Comment by anuress** [comment]
Hmm, it's not sdk problem, I guess? Anyway, thank you, it's working now.

**Comment by adicatur** [comment]
Cool!, the issue was on Server, but we've fixed it, anyway thanks for the report
