### ISSUE TITLE
NullPointerException at QiscusSyncJobService.java:143

### ISSUE THREAD

**Issue by quyvv** [qiscus/qiscus-sdk-android#96]
I meet this issue for a long time, even after upgrade to the latest qiscusCore version 1.3.30
![qiscus crash](https://user-images.githubusercontent.com/80660601/122350959-dfef6c80-cf77-11eb-98b3-fbe66d92be2d.PNG)
![crash info](https://user-images.githubusercontent.com/80660601/122350973-e2ea5d00-cf77-11eb-8e44-d35309119a5b.PNG)
I've looked at the SDK source code and saw this line got crashed:
`
private void stopSync() {
        if (timer != null) {
            timer.cancel();
            timer.purge();
            timer = null;
        }
 }
`
The stopSync only got called in log out and onDestroy service.
In fact, this release note should fix that issue https://github.com/qiscus/qiscus-sdk-android/releases/tag/1.3.20 but I'm using 1.3.30 and it still occurred.

**Comment by adicatur** [comment]
Hi @quyvv, thanks for this, 

We will look into it, and let you know the update

Regards

**Comment by quyvv01581** [comment]
any update about this issue @adicatur @ariefnurputranto @huseinmuhdhor ?

**Comment by ariefnurputranto** [comment]
@quyvv01581 , you can use this version sir. https://github.com/qiscus/qiscus-sdk-android/releases/tag/1.3.31

**Comment by quyvv01581** [comment]
Thanks, @ariefnurputranto, I will try to test on this version and paste the result here later on
