### ISSUE TITLE
Insecure Storage of Sensitive Data

### ISSUE THREAD

**Issue by BalvinderSingh23** [qiscus/qiscus-sdk-android#97]
Hi Team,

During testing of an application we came to know that they are storing qiscus.cfg.xml files through which some of keys are been disclosed.

In Line #1005 It is also mentioned:
LocalDataManager() {
            sharedPreferences = QiscusCore.getApps().getSharedPreferences("qiscus.cfg", Context.MODE_PRIVATE);
            gson = new Gson();
            token = isLogged() ? getAccountInfo().getToken() : "";
            
            
Isn't it a security threat ?
As an attacker can steal the qiscus authorization tokens from here.

**Comment by ariefnurputranto** [comment]
hi @BalvinderSingh23 

Thank you for your report,
Currently our team is researching best method to patch the security finding.

**Comment by ariefnurputranto** [comment]
Hi @BalvinderSingh23 

Thank you for your report,
Currently our team is researching best method to patch the security finding.

**Comment by ariefnurputranto** [comment]
hi @BalvinderSingh23 , 

We have released new sdk core to solve this problem,
you can check the changelog and notes from this link (https://github.com/qiscus/qiscus-sdk-android/releases/tag/1.4.0)


Thanks

**Comment by BalvinderSingh23** [comment]
Hi @ariefnurputranto ,
This issue still persists.

**Comment by ariefnurputranto** [comment]
hi @BalvinderSingh23 

We have changed the regular sharedPref storage to the encrypted SharedPref storage, and the attacker can't get the token from this file. can you explain where the problem is still going sir?
